name: Docker Image CI

on:
  push:
    tags:
    - '*'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: DEV
        required: true
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
